language: node_js
node_js:
- '5'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token: a2be0e92be0d033998b45833a094476a26767d9fa26ab5f43179f19025433342
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  on:
    tags: true
    branches: true
  api_key:
    secure: APqr0ewEBpJzmUgQwWWB1esl+BmWZK1JB5ZWJd1of8rg2YyyDv2U+vXhl477/1q22AE562oTkDXGSCzhHbGMTz1XRJ+9XzxRArhsMH5Krb+c6nNgcad2+BgmSpRyNQG9d+0qjH/2U2KpFwruJ3vZkFctW+FUZvK3seukkRVDBOSIHjoN2hZkGx7lfIgJgN33IVqKygLzXkjw3r35oLve55l5s7WNsQ66TYcVTJL40gjJ//1uLsj5epAeiRzE9HBJpjpHtvRmjYFrWL2cKqbHvSQ2dDwRBzBB54zq8/0ad9Akqb1nmLsskD1QmSObswxcStKvJFiIzNPS/ysZm4b54P67qX2dsEVr2Tte7QZ2kmLEYjMmL9h/IWH2Zt4Sk+SB88Ts3mFQo4GC17l2US0c8/9cfSTkh9jIpwSWkFzV+a/B71D6xkUIP/y/2XnT5MG7RX611JkQXJQS4i7mzctf0KCKCJy7oOY4BJvU1tIaqcLeocSpEXm3Hj7TDylq2y/k74acw2ScFZkxlDEWPDICdNfJYrDFsPm/oKM+B8+lUXGYmSO7kx9aHkof44KU0kWSYFTZnzjxJv5P44eTK9wJQpHBb6UOFrveRSMrR7GN4MGEMOYJu4DQg5KcI+BVlKOfKVXOXT4OJbSRtm4+DB4wmBR2Rq2/DO+fmpsdIX0gzJY=
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - "/^v[0-9]/"
